/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela.admin;

import Tela.TelaCadastroDeUsuario;
import Tela.Utils;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Admin;
import model.bean.Usuario;
import model.dao.UsuarioDao;

/**
 *
 * @author Kazuto
 */
public class TelaHomeAdmin extends javax.swing.JFrame {

    private Admin admin;
    /**|
     * Creates new form TelaHomeAdmin
     */
    public TelaHomeAdmin(Admin adminLogado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.admin = adminLogado;
        jLabelBemVindo.setText("Bem-vindo " + admin.getNome());
        readJTable();
        Utils.setIcon(this);
    }

    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        
        UsuarioDao dao = new UsuarioDao();
        for(Usuario u:dao.read()){
            modelo.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getDataNasc()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jLabelBemVindo = new javax.swing.JLabel();
        jTUsuarios = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        attBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Perfil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addBtn.setText("Adicionar usuário");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabelBemVindo.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Idade"
            }
        ));
        jTUsuarios.setViewportView(jTable1);

        attBtn.setText("Atualizar usuário");
        attBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Deletar usuário");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBemVindo)
                        .addGap(439, 439, 439)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(delBtn)
                            .addGap(18, 18, 18)
                            .addComponent(attBtn)
                            .addGap(18, 18, 18)
                            .addComponent(addBtn))
                        .addComponent(jTUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBemVindo)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jTUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(attBtn)
                    .addComponent(delBtn))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        TelaCadastroDeUsuario cadastro = new TelaCadastroDeUsuario(admin);
        cadastro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() != -1){
            int id = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            String nome = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 1);
            
            int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar o usuario \"" + nome+ "\"?",
                                                                  "Confirmação",
                                                                  JOptionPane.YES_NO_OPTION);
            
            if(confirmacao == JOptionPane.YES_OPTION){
                Usuario u = new Usuario();
                UsuarioDao dao = new UsuarioDao();
                u.setId(id);
                dao.delete(u);
                readJTable();
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um usuario para deletar.");
            }
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void attBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attBtnActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() != -1){
            int idSelecionado = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            UsuarioDao dao = new UsuarioDao();
            Usuario usuario = dao.readById(idSelecionado);
            
            TelaAtualizarUsuario telaAtt = new TelaAtualizarUsuario(admin, usuario);
            telaAtt.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um usuario para atualizar");
        }
    }//GEN-LAST:event_attBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new TelaHomeAdmin().setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton attBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JScrollPane jTUsuarios;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
